[phases.setup]
cmds = ["chmod +x ./mvnw"]

[phases.build]
cmds = [
  "./mvnw dependency:go-offline -B",
  "./mvnw clean package -DskipTests -Dmaven.javadoc.skip=true",
  "ls -la target/",
  "find target -name '*.jar' -type f"
]

[phases.start]
cmd = "java -Dserver.port=$PORT -jar $(find target -name '*.jar' -not -name '*sources*' -not -name '*javadoc*' | head -1)"

[variables]
MAVEN_OPTS = "-Xmx1024m -XX:MaxMetaspaceSize=256m"
JAVA_TOOL_OPTIONS = "-Xmx1g"
