[phases.setup]
nixPkgs = ["jdk21", "maven"]
cmds = ["chmod +x ./mvnw"]

[phases.build]
cmds = [
  "rm -rf target/",
  "./mvnw dependency:go-offline -B",
  "./mvnw clean package -DskipTests -Dmaven.javadoc.skip=true",
  "mkdir -p uploads/images",
  "ls -la target/",
  "find target -name '*.jar' -type f"
]

[phases.start]
cmd = "java -Dspring.profiles.active=prod -Xmx512m -jar target/blog-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Xmx512m -XX:MaxMetaspaceSize=128m"
SPRING_PROFILES_ACTIVE = "prod"
