services:
  - type: web
    name: blog-api
    env: java
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m -XX:MaxMetaspaceSize=128m"
    plan: free

databases:
  - name: blog-db
    databaseName: blog
    user: blog_user
    plan: free